#  Copyright (c) 2026 Cisco Systems, Inc. and its affiliates
#  SPDX-License-Identifier: Apache-2.0
# HITL on tool egress and tool-result ingress — sample_governance plugin.
# hitl_mode: interactive prompts operator; auto-approve for CI/bench.
apiVersion: mas/v1
kind: Overlay
metadata:
  name: governance-hitl
spec:
  patch:
    governance:
      - sample_governance:
          hitl_on_tool: true
          hitl_on_tool_result: true
          hitl_once_per_turn: false
          hitl_mode: interactive
