#  Copyright (c) 2026 Cisco Systems, Inc. and its affiliates
#  SPDX-License-Identifier: Apache-2.0
apiVersion: mas/v1
kind: Overlay
metadata:
  name: reflection-moderator
spec:
  target:
    kind: MAS
  patch:
    agents:
      moderator:
        design_pattern:
          type: reflection
          config:
            max_steps: 10
x-namespace: trip-planner
x-canvas-positions:
  node_39208426:
    x: 848
    y: 128
  node_05f64466:
    x: 496
    y: 144
x-canvas-node-ids:
  moderator:
    agent: node_39208426
    designPattern: node_05f64466
