apiVersion: mas/v1
kind: MAS
metadata:
  name: concierge-lite
spec:
  agency:
    agents:
      - id: concierge-lite
        ref: agents/concierge-lite.yaml
  workflow:
    entry: concierge-lite
    nodes:
      - id: concierge-lite
        role: specialist
x-canvas-positions:
  node_87698413:
    x: 496
    y: 160
  node_dfd2af13:
    x: -32
    y: 144
  node_f3e7848a:
    x: -32
    y: 432
  node_f993b79d:
    x: -48
    y: 672
  node_a998bc5a:
    x: -48
    y: 976
