#  Copyright (c) 2026 Cisco Systems, Inc. and its affiliates
#  SPDX-License-Identifier: Apache-2.0
apiVersion: mas/v1
kind: RuntimeDefaultsManifest
metadata:
  name: runtime-default-defaults
spec:
  model: gpt-4o-mini
  design_pattern: react@v1
  context_manager: sliding-window
