#  Copyright (c) 2026 Cisco Systems, Inc. and its affiliates
#  SPDX-License-Identifier: Apache-2.0
apiVersion: mas/v1
kind: Overlay
metadata:
  name: skill-impl-native
spec:
  target:
    kind: Agent
  patch:
    tools:
      $op:
        remove:
          - ref: "skills:tools/skill-access.tool.yaml"
          - ref: "skills:tools/run-skill-script.tool.yaml"
        add:
          - ref: "skills:tools/skill-access.tool.yaml"
            params:
              impl: native
              base_dir: ./skills/
          - ref: "skills:tools/run-skill-script.tool.yaml"
            params:
              impl: native
              base_dir: ./skills/
