#  Copyright (c) 2026 Cisco Systems, Inc. and its affiliates
#  SPDX-License-Identifier: Apache-2.0
# Overlay — live LLM via workspace/user infra
apiVersion: mas/v1
kind: Overlay
metadata:
  name: live-llm
spec:
  patch:
    execution:
      mocking:
        enabled: false
      cache:
        enabled: true
    llm:
      provider: openai
      temperature: 0.7
      max_tokens: 2000
