#  Copyright (c) 2026 Cisco Systems, Inc. and its affiliates
#  SPDX-License-Identifier: Apache-2.0
# Overlay — hints mock LLM for tutorials/CI. Actual backend comes from workspace
# infra_refs (standard:mock-llm), MAS_INFRA_REFS, --infra-ref, or mas-lab
# benchmark --infra — never agent/MAS/overlay infra_refs in this patch.
apiVersion: mas/v1
kind: Overlay
metadata:
  name: mock-llm
spec:
  target:
    kind: Agent
  patch:
    llm:
      provider: mock
