#  Copyright (c) 2026 Cisco Systems, Inc. and its affiliates
#  SPDX-License-Identifier: Apache-2.0
# Overlay — native JSONL observability
apiVersion: mas/v1
kind: Overlay
metadata:
  name: observability-native
spec:
  patch:
    observability:
      - native
