#  Copyright (c) 2026 Cisco Systems, Inc. and its affiliates
#  SPDX-License-Identifier: Apache-2.0
# Live OTel plugin: JSONL plus OTLP. An infra OtelCollector manifest is
# optional — set $OTEL_EXPORTER_OTLP_ENDPOINT and add the otel plugin
# (this overlay, or spec.observability.plugins: [otel]).
apiVersion: mas/v1
kind: Overlay
metadata:
  name: observability-otel-collector
spec:
  target:
    kind: Agent
  patch:
    observability:
      $op:
        replace:
          - otel:
              output_path: traces/otel_sdk_spans.jsonl
              converter_profile: observe_sdk
              otlp_endpoint_env: OTEL_EXPORTER_OTLP_ENDPOINT
