apiVersion: lab/v1
kind: Dataset
metadata:
  name: trip-planner/tutorial-queries
spec:
  items:
    - id: 1
      inputs:
        user:
          - role: user
            content: What trains run from Celestia to Verdantia?
    - id: 2
      inputs:
        user:
          - role: user
            content: What are the main attractions in Celestia?
    - id: 3
      inputs:
        user:
          - role: user
            content: How much does a flight from Celestia to Luminos cost?
