#  Copyright (c) 2026 Cisco Systems, Inc. and its affiliates
#  SPDX-License-Identifier: Apache-2.0
# HITL on tool egress and tool-result ingress — sample_governance plugin.
apiVersion: mas/v1
kind: Overlay
metadata:
  name: hitl-on-tool
spec:
  patch:
    governance:
      - sample_governance:
          hitl_on_tool: true
          hitl_on_tool_result: true
          hitl_mode: interactive
