#  Copyright (c) 2026 Cisco Systems, Inc. and its affiliates
#  SPDX-License-Identifier: Apache-2.0
"""AUTO-GENERATED by scripts/gen_schema_artifacts.py — do not edit."""

from __future__ import annotations

LLM_BINDING_KEYS = frozenset(
    {
    'max_tokens',
    'model',
    'provider',
    'temperature',
    }
)

EXECUTION_BINDING_KEYS = frozenset(
    {
    'cache',
    'engine_queue_depth',
    'live',
    'max_auto_steps',
    'mocking',
    'parallel',
    'stream',
    'timeout',
    }
)

EXECUTION_MOCKING_KEYS = frozenset(
    {
    'enabled',
    }
)

EXECUTION_CACHE_KEYS = frozenset(
    {
    'enabled',
    'read',
    'write',
    }
)

CONTROL_BINDING_KEYS = frozenset(
    {
    'budget',
    'circuit_breaker',
    'rate_limiter',
    }
)

DESIGN_PATTERN_BINDING_KEYS = frozenset(
    {
    'config',
    'params',
    'ref',
    'type',
    }
)

CONTEXT_MANAGER_BINDING_KEYS = frozenset(
    {
    'memory',
    'params',
    'ref',
    'type',
    }
)

CONTEXT_MANAGER_ASSEMBLY_PARAM_KEYS = frozenset(
    {
    'max_in_turn_messages',
    'max_tokens',
    'reserve_tokens',
    'token_budget',
    'token_budget_ref',
    'trimmer_ref',
    'working_memory_messages',
    'working_memory_ref',
    }
)

CONTEXT_MANAGER_STRATEGY_PARAM_KEYS = frozenset(
    {
    'keep_turns',
    'max_messages',
    'max_turns',
    'summary_threshold',
    'window_size',
    }
)

