#  Copyright (c) 2026 Cisco Systems, Inc. and its affiliates
#  SPDX-License-Identifier: Apache-2.0
"""AUTO-GENERATED by scripts/gen_schema_artifacts.py — do not edit."""

from __future__ import annotations

LLM_BINDING_KEYS = frozenset(
    {
    'extra',
    'frequency_penalty',
    'logit_bias',
    'logprobs',
    'max_completion_tokens',
    'max_tokens',
    'metadata',
    'min_p',
    'min_tokens',
    'modalities',
    'model',
    'n',
    'parallel_tool_calls',
    'prediction',
    'presence_penalty',
    'prompt_cache_key',
    'provider',
    'reasoning',
    'reasoning_effort',
    'repetition_penalty',
    'response_format',
    'seed',
    'service_tier',
    'stop',
    'store',
    'temperature',
    'top_k',
    'top_logprobs',
    'top_p',
    'user',
    'verbosity',
    }
)

EXECUTION_BINDING_KEYS = frozenset(
    {
    'cache',
    'engine_queue_depth',
    'live',
    'max_auto_steps',
    'parallel',
    'stream',
    'timeout',
    }
)

EXECUTION_CACHE_KEYS = frozenset(
    {
    'enabled',
    'read',
    'write',
    }
)

CONTROL_BINDING_KEYS = frozenset(
    {
    'budget',
    'circuit_breaker',
    'rate_limiter',
    }
)

DESIGN_PATTERN_BINDING_KEYS = frozenset(
    {
    'config',
    'params',
    'ref',
    'type',
    }
)

CONTEXT_MANAGER_BINDING_KEYS = frozenset(
    {
    'memory',
    'params',
    'ref',
    'type',
    }
)

ASSEMBLER_BINDING_KEYS = frozenset(
    {
    'params',
    'ref',
    'type',
    }
)

CONTEXT_MANAGER_ASSEMBLY_PARAM_KEYS = frozenset(
    {
    'max_in_turn_messages',
    'trimmer',
    'working_memory_messages',
    'working_memory_ref',
    }
)

CONTEXT_MANAGER_STRATEGY_PARAM_KEYS = frozenset(
    {
    'hysteresis_ratio',
    'keep_turns',
    'max_messages',
    'max_turns',
    'summarizer',
    'summary_threshold',
    'window_size',
    }
)

INFRA_MIDDLEWARE_PATH_PARAM_KEYS = frozenset(
    {
    'cache_path',
    'miss_log_path',
    'path',
    }
)

