#  Copyright (c) 2026 Cisco Systems, Inc. and its affiliates
#  SPDX-License-Identifier: Apache-2.0
"""AUTO-GENERATED by scripts/gen_schema_artifacts.py — do not edit."""

from __future__ import annotations

EXECUTION_MAX_AUTO_STEPS = 512
EXECUTION_ENGINE_QUEUE_DEPTH = 32
CONTEXT_MANAGER_WORKING_MEMORY_MESSAGES = 20
CONTEXT_MANAGER_RESERVE_TOKENS = 512
