apiVersion: mas/v1
kind: MAS
metadata:
  name: qa-mas
spec:
  agency:
    agents:
      - id: qa-agent
        ref: agents/qa-agent.yaml
  workflow:
    type: dynamic
    entry: qa-agent
    nodes:
      - id: qa-agent
        role: specialist
x-canvas-positions:
  node_3d1113bc:
    x: 624
    y: 64
  node_98e08fad:
    x: 112
    y: 96
  node_f665d7f6:
    x: 96
    y: 400
  node_02f6d7ad:
    x: 112
    y: 656
  node_db6794a6:
    x: 144
    y: 928
