authors:
  mas.team:
    name: MAS Lab Team
    description: Outshift open-source maintainers
    url: https://github.com/outshift-open/mas-lab
    avatar: https://github.com/outshift-open.png
  giovanna.carofiglio:
    name: Giovanna Carofiglio
    description: Outshift by Cisco
    avatar: https://github.com/outshift-open.png
  jordan.auge:
    name: Jordan Augé
    description: Outshift by Cisco
    avatar: https://github.com/outshift-open.png
  mayank.gupta:
    name: Mayank Gupta
    description: Outshift by Cisco
    avatar: https://github.com/outshift-open.png
