//  Copyright (c) 2026 Cisco Systems, Inc. and its affiliates
//  SPDX-License-Identifier: Apache-2.0
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for kind: Agent manifests (apiVersion: mas/v1). Authoritative field list is derived from AgentSpec in agent.py. Validate with: python -m jsonschema --instance my-agent.yaml agent.schema.yaml
 *
 */
export interface AgentManifest {
  apiVersion: "mas/v1";
  kind: "Agent";
  metadata: {
    /**
     * Agent ID — must match the workflow node id that references this agent.
     */
    name: string;
    /**
     * Human-readable description of this agent.
     */
    description?: string;
    version?: string;
    /**
     * Free-form tags for filtering and grouping.
     */
    tags?: string[];
  };
  spec: {
    /**
     * Flat key-value context dict injected into the system prompt by DefaultContextPlugin.  Well-known keys: intent, role.  Values starting with ./ are treated as file references resolved relative to the agent manifest directory.
     *
     */
    context?: {
      [k: string]: string;
    };
    /**
     * Routing-facing description for delegation tools and AgentCard. Write from the delegator's perspective. Priority: spec.description > spec.role.description > spec.context.intent.
     *
     */
    description?: string;
    /**
     * Application-level purpose of this agent — shared context injected into the system prompt. In single-agent deployments, written directly here. In multi-agent deployments, defined once in the MAS config and injected via overlay. Used as the AgentCard description fallback when role.description is empty.
     *
     */
    intent?: string;
    /**
     * The ONLY place for system prompt configuration in kind: Agent. role.description  → routing-facing one-liner for orchestrator LLMs; falls back to intent. role.instructions → inline system prompt (mutually exclusive with instructions_ref). role.instructions_ref → external reference (mutually exclusive with instructions).
     *
     */
    role?: {
      /**
       * Routing-optimised one-liner surfaced as the delegate_to_<id> tool description seen by the orchestrator's LLM. Write it from the delegator's perspective: "Call me when you need X. I return Y." Used for AgentCard; falls back to spec.intent when empty.
       *
       */
      description?: string;
      /**
       * Inline system prompt — the full text injected before every LLM call. Mutually exclusive with instructions_ref.
       *
       */
      instructions?: string;
      /**
       * External reference to the system prompt.  Three forms: - Plain text file:  "./prompts/broker.md"  (Markdown / plain text, Jinja2 ok) - XPointer:  "./prompts/sre-prompts.yaml#broker-role"
       *   File must be a kind: PromptBundle YAML; the fragment selects the entry key.
       * - Library ref:  "@sre-prompts#broker-role"
       *   Searches for sre-prompts.yaml in prompts/ then manifest directory.
       * Mutually exclusive with instructions.
       *
       */
      instructions_ref?: string | null;
      /**
       * Few-shot examples for this agent's role, injected before the first user message. Each entry is inline (prompt + response), a plain YAML list file (ref: ./examples/qa.yaml), an XPointer (ref: ./prompts/sre.yaml#broker-examples), or a library ref (ref: @sre-prompts#broker-examples).
       *
       */
      examples?: {
        /**
         * Ref forms: ./path/file.yaml (plain list), ./bundle.yaml#key (XPointer), or @lib-name#key (library ref).
         *
         */
        ref?: string;
        /**
         * Inline user-side prompt text.
         */
        prompt?: string;
        /**
         * Inline expected response text.
         */
        response?: string;
      }[];
    };
    /**
     * Preferred model(s) for this agent. Structural intent only — the active flavour selects the actual provider at runtime. Do NOT put api_base or api_key_env here.
     *
     */
    models?: {
      /**
       * Logical model ID within this agent. Use 'main' for the primary model.
       */
      id?: string;
      /**
       * LiteLLM-style model string, e.g. vertex_ai/gemini-3-pro-preview.
       */
      model: string;
      temperature?: number;
      max_tokens?: number;
    }[];
    /**
     * Reasoning strategy. Defaults to react if absent.
     */
    design_pattern?: {
      /**
       * Builtin name shorthand — mutually exclusive with ref. react | cot | cot_native | plan_execute | tree_of_thoughts | accumulator | role aliases. Equivalent to ref: <name> when no scheme prefix.
       *
       */
      type?: string;
      /**
       * Unified plugin locator — mutually exclusive with type. Forms: bare-name, ./local/path, module://pkg.Class, oci://registry/img:tag
       *
       */
      ref?: string;
      /**
       * Pattern-specific parameters, e.g. max_steps for CoT.
       */
      params?: {
        [k: string]: unknown;
      };
    };
    /**
     * Context window management strategy. Defaults to stack (StackConversation, unbounded history) when absent. Builtin types: stack | sliding-window | summarising | full-history.
     *
     */
    context_manager?: {
      /**
       * Builtin name shorthand — mutually exclusive with ref: stack | sliding-window | summarising | full-history.
       */
      type?: string;
      /**
       * Unified plugin locator — mutually exclusive with type. Same forms as design_pattern.ref.
       */
      ref?: string;
      /**
       * Strategy-specific constructor kwargs, e.g. {max_turns: 10} for sliding-window.
       */
      params?: {
        [k: string]: unknown;
      };
      /**
       * Skill names to auto-inject into the system prompt via ContextFacetProvider.  Resolved by proximity search the same way spec.skills are.  This is the context path — complements the tool path (spec.skills → consult_skills tool).
       *
       */
      skills?: string[];
      /**
       * Memory types whose content is auto-injected into the system prompt as context facets.  E.g. [semantic].
       *
       */
      memory?: string[];
    };
    /**
     * Path to the shared skills directory (AgentSkills.io layout). Relative paths are resolved from the agent manifest directory. E.g. ../../skills — points to skills/ at the app root.
     *
     */
    skills_dir?: string;
    /**
     * Documents to pre-index into the memory backend at startup. Useful for demos and tests that need pre-populated memory without a persistent store.  Each entry is indexed via index_document(source, content, metadata?).
     *
     */
    memory_seed?: {
      /**
       * Short label for the origin, e.g. 'user_preference'.
       */
      source?: string;
      /**
       * The text content to store in memory.
       */
      content: string;
      /**
       * Optional metadata dict attached to the document.
       */
      metadata?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }[];
    /**
     * Memory configuration for this agent.  Three forms: - String shorthand: "semantic" — resolved to plugin bundle. - Array shorthand: ["semantic", "episodic"] — multiple bundles. - Full object: memory.types, memory.compaction, etc. When absent, the active flavour decides defaults.
     *
     */
    memory?:
      | string
      | string[]
      | {
          /**
           * Master switch.  false = no memory plugins loaded.
           */
          enabled?: boolean;
          /**
           * Ordered list of memory layers to activate.  The runtime instantiates one MemoryProviderPlugin per entry.  When absent, the flavour decides which layers to activate.
           *
           */
          types?: {
            /**
             * Memory layer name: session | episodic | semantic | working | procedural.
             *
             */
            name: string;
            /**
             * Backend implementation: in-memory | file | sqlite-vec | redis | remote_tool.
             *
             */
            backend?: string;
            /**
             * Backend-specific parameters (path, url, collection, etc.).
             */
            params?: {
              [k: string]: unknown;
            };
          }[];
          /**
           * Conversation compaction configuration.  Controls how old turns are summarized to stay within the context window.  Maps to the ConversationStrategy used by ContextAssemblerPlugin.
           *
           */
          compaction?: {
            /**
             * Compaction strategy name: keep_recent | summarize | chunked_summarize. chunked_summarize splits long context into multiple summarized chunks.
             *
             */
            strategy?: string;
            /**
             * Minimum tokens reserved for the LLM reply.
             */
            reserve_tokens?: number;
            /**
             * Fraction of recent messages to preserve verbatim (0.0–1.0).
             */
            keep_recent_ratio?: number;
            /**
             * Minimum fraction per compaction chunk.
             */
            min_chunk_ratio?: number;
            /**
             * Buffer multiplier for token estimation error.
             */
            safety_margin?: number;
            /**
             * Preserve opaque identifiers (UUIDs, hashes, URLs, file names) during summarization.
             *
             */
            identifier_preservation?: boolean;
            /**
             * Custom instructions prepended to the summarization prompt.
             */
            summarize_instructions?: string;
          };
          /**
           * Session transcript persistence.  Controls where and how conversation history is saved between runs.
           *
           */
          persistence?: {
            /**
             * Persistence backend: none | file | sqlite | redis.
             */
            backend?: string;
            /**
             * Base directory for file-based persistence.  Supports {agent_id} and {session_id} placeholders.  Default: ~/.mas/agents/{agent_id}/sessions/
             *
             */
            path?: string;
            /**
             * Automatically persist after each turn.
             */
            auto_save?: boolean;
            /**
             * Automatically load session on bootstrap.
             */
            auto_load?: boolean;
          };
          /**
           * Semantic memory search configuration.  Controls vector retrieval from the semantic memory layer.
           *
           */
          search?: {
            /**
             * Enable semantic search injection into context.
             */
            enabled?: boolean;
            /**
             * Maximum retrieved chunks per query.
             */
            max_results?: number;
            /**
             * Minimum similarity score threshold.
             */
            min_score?: number;
            chunking?: {
              /**
               * Chunk size in tokens for indexing.
               */
              tokens?: number;
              /**
               * Overlap tokens between chunks.
               */
              overlap?: number;
            };
            /**
             * Hybrid search (vector + full-text) configuration.
             */
            hybrid?: {
              enabled?: boolean;
              vector_weight?: number;
              text_weight?: number;
              /**
               * Max Marginal Relevance re-ranking.
               */
              mmr_enabled?: boolean;
              mmr_lambda?: number;
              temporal_decay_enabled?: boolean;
              temporal_decay_half_life_days?: number;
            };
            cache?: {
              enabled?: boolean;
              max_entries?: number;
            };
          };
          /**
           * Citation formatting for memory search results. Controls whether and how source references are included in search results injected into context.
           *
           */
          citations?: {
            /**
             * Citation mode: auto (include when useful), on (always include), off (strip source info). Controls citation presentation for memory results.
             *
             */
            mode?: "auto" | "on" | "off";
            /**
             * Maximum characters per search result snippet.
             */
            max_snippet_chars?: number;
          };
          /**
           * File watching and re-indexing synchronization policy. Controls when workspace memory files (MEMORY.md, memory/*.md) are re-indexed into semantic memory.
           *
           */
          sync?: {
            /**
             * Re-index when a session begins.
             */
            on_session_start?: boolean;
            /**
             * Re-index before search (ensures fresh results).
             */
            on_search?: boolean;
            /**
             * Periodic re-index interval in seconds (0 = disabled).
             */
            interval_seconds?: number;
            /**
             * Re-index after this many new messages.
             */
            delta_messages?: number;
            /**
             * Re-index after this many bytes of new content.
             */
            delta_bytes?: number;
            /**
             * Force re-index after compaction.
             */
            post_compaction_force?: boolean;
            /**
             * File change detection settings.
             */
            file_watch?: {
              enabled?: boolean;
              /**
               * Glob patterns to watch for changes.
               */
              patterns?: string[];
              /**
               * Debounce interval for file change detection.
               */
              debounce_ms?: number;
            };
          };
          /**
           * Compaction retry on context overflow.  When an LLM call fails because the context exceeds the window, automatically compact and retry.
           *
           */
          overflow_retry?: {
            /**
             * Enable overflow detection and automatic retry.
             */
            enabled?: boolean;
            /**
             * Maximum compaction+retry attempts.
             */
            max_retries?: number;
            /**
             * Maximum total time for all retries.
             */
            aggregate_timeout_seconds?: number;
            /**
             * Multiply budget by this factor on each retry.
             */
            budget_reduction_factor?: number;
          };
          /**
           * QMD (Qualitative Memory Database) backend configuration. Alternative search via external qmd binary.
           *
           */
          qmd?: {
            /**
             * Enable QMD as a retriever backend.
             */
            enabled?: boolean;
            /**
             * Path to qmd binary (auto-detected if empty).
             */
            binary_path?: string;
            /**
             * Path to QMD index directory.
             */
            index_path?: string;
            /**
             * QMD search mode.
             */
            search_mode?: string;
            max_snippet_chars?: number;
            timeout_seconds?: number;
          };
        };
    /**
     * Skill ids to activate (hyphenated names matching skills/<name>/SKILL.md under the app root). E.g. triage-protocol, memory-protocol. Library skills use @library/name.
     *
     */
    skills?: string[];
    /**
     * Logical tool-set name resolved by the infra manifest ToolRegistry. No file paths, no extensions — a simple identifier only. The infra ToolRegistry maps this name to the actual JSON tool-index file path. E.g. sre-tools, backend-tools, verifier-tools.
     *
     */
    tools_ref?: string | null;
    /**
     * Tool declarations for this agent.  Three forms are supported:
     * Form A — ref to a kind: Tool manifest (recommended):
     *   tools:
     *     - ref: ./tools/calculator.tool.yaml
     *     - ref: bundle://sre-tools/check-health   # ToolBundle entry
     *
     * Form B — inline anonymous (backward-compatible):
     *   tools:
     *     - module_path: library-samples/tools/calc.py
     *       class_name: CalculatorTool
     *
     * Additive with tools_ref — both may be set simultaneously.
     *
     */
    tools?: (
      | string
      | {
          /**
           * Path to a kind: Tool manifest (./tools/calculator.tool.yaml) or a ToolBundle entry reference (bundle://sre-tools/check-health).
           *
           */
          ref: string;
          /**
           * Registration priority (higher = loaded first).
           */
          priority?: number;
        }
      | {
          /**
           * Implementation kind — defaults to python. python  — ToolContract subclass loaded via module_path. remote_tool — remote tool-server tool; module_path points to ToolServerClient adapter. openapi — OpenAPI endpoint; module_path points to OpenAPITool adapter.
           *
           */
          kind?: "python" | "remote_tool" | "openapi";
          /**
           * Dotted Python module path, e.g. library-samples/tools/calc.py. May also be a relative filesystem path (./tools/my_tool.py).
           *
           */
          module_path: string;
          /**
           * Class name in the module. Auto-discovered when omitted.
           */
          class_name?: string;
          /**
           * Registration priority (higher = loaded first).
           */
          priority?: number;
          /**
           * Optional tool-specific init params.
           */
          params?: {
            [k: string]: unknown;
          };
        }
    )[];
    /**
     * Plugin instances to load into this agent's registry. Processed in order — use priority to control execution ordering within hook chains. Overlay-compatible: an overlay may append entries to this list or override a named entry (matched by the name field).
     *
     */
    plugins?: {
      /**
       * Logical name for this plugin instance. Used as a stable key for overlay merge and registry lookup. Defaults to class_name when omitted.
       *
       */
      name?: string;
      /**
       * Dotted Python module path, e.g. mas.runtime.plugins.guardrails_plugin.
       */
      module_path: string;
      /**
       * Plugin class name to instantiate.
       */
      class_name: string;
      /**
       * Plugin-specific init kwargs passed as plugin_cls(**config).
       */
      config?: {
        [k: string]: unknown;
      };
      /**
       * Alias for config (backward compatibility).
       */
      params?: {
        [k: string]: unknown;
      };
      /**
       * Execution order within a hook chain. Lower = earlier.
       */
      priority?: number;
      /**
       * Set to false to disable this plugin without removing it.
       */
      enabled?: boolean;
    }[];
    /**
     * Per-agent runtime behavior configuration. These settings are structural/semantic — they affect what system tools and capabilities are exposed to this agent's LLM at runtime. Do NOT put secrets, API keys, or deployment config here (use flavour.yaml).
     *
     */
    behavior?: {
      /**
       * When true, the send_to_caller tool exposes an optional reasoning_context parameter.  The sub-agent can (but is not required to) provide a concise summary of HOW it reached its answer — not its message history, but key evidence, decision points, and confidence signals. Forwarded to the orchestrator as result["reasoning"] so it can bridge the cognitive gap between delegation and synthesis. Privacy-by-default: false.  Enable only for trusted internal agents where context leakage is acceptable.
       *
       */
      share_reasoning?: boolean;
      /**
       * Controls which delegation tools are registered for this agent.
       * typed (default): Only delegate_to_<id> tools are available.
       *   The set of reachable agent IDs is static (registered by MasRuntime
       *   from the workflow topology).  The LLM cannot hallucinate an agent_id
       *   that does not exist in the topology.  Preferred for production MAS.
       *
       * generic: In addition to typed tools (if any), GenericDelegationPlugin
       *   is registered, exposing delegate_task(agent_id, task).  The LLM
       *   provides the agent_id as a free string — no static validation.
       *   Used by LangChain, ADK, AutoGen, Bedrock.  Acceptable for fully
       *   dynamic / open-world topologies where agent IDs are not known at
       *   manifest-load time.
       *
       */
      delegation_style?: "typed" | "generic";
    };
  };
}
