/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * One named system-prompt chunk under spec.context. Inline string, a path starting with ./ or ../, or an explicit ref object.
 *
 */
export type ContextChunk =
  | string
  | {
      /**
       * File path relative to the agent manifest directory.
       */
      ref: string;
    };
/**
 * Governance plugin list (ordered plugin stanzas).
 *
 */
export type GovernanceBinding = (
  | ("sample_governance" | "sample_governance@v1")
  | {
      sample_governance?: {
        hitl_on_tool?: boolean;
        hitl_on_tool_result?: boolean;
        hitl_once_per_turn?: boolean;
        hitl_mode?: "interactive" | "auto-approve" | "auto-deny" | false;
        gov_policy_profile?: string;
        gov_block_destructive?: boolean;
        gov_trigger_destructive?: boolean;
        gov_ingress_profile?: string;
        max_cot_pass?: number;
        max_gov_retries?: number;
        policies?: PolicyRule[];
      };
      "sample_governance@v1"?: {
        hitl_on_tool?: boolean;
        hitl_on_tool_result?: boolean;
        hitl_once_per_turn?: boolean;
        hitl_mode?: "interactive" | "auto-approve" | "auto-deny" | false;
        gov_policy_profile?: string;
        gov_block_destructive?: boolean;
        gov_trigger_destructive?: boolean;
        gov_ingress_profile?: string;
        max_cot_pass?: number;
        max_gov_retries?: number;
        policies?: PolicyRule1[];
      };
    }
)[];
/**
 * List of observability sink plugin ids (OSS: native, otel). Plugin implementations are resolved at runtime from the plugin registry — unknown ids fail at load time. Extended sinks (observe_sdk, etc.) are internal-only; see mas-lab-internal.
 *
 */
export type ObservabilityBinding = (
  | ("native" | "otel")
  | {
      native?: {
        path?: string;
        events_file?: string;
      };
      otel?: {
        output_path?: string;
        otel_file?: string;
      };
    }
)[];

/**
 * Schema for kind: Agent manifests (apiVersion: mas/v1). Authoritative field list is derived from AgentSpec in agent.py. Validate with: python -m jsonschema --instance my-agent.yaml agent.schema.yaml
 *
 */
export interface AgentManifest {
  apiVersion: "mas/v1";
  kind: "Agent";
  metadata: {
    /**
     * Agent ID — must match the workflow node id that references this agent.
     */
    name: string;
    /**
     * Human-readable description of this agent.
     */
    description?: string;
    version?: string;
    /**
     * Free-form tags for filtering and grouping.
     */
    tags?: string[];
  };
  spec: {
    /**
     * Named chunks injected into the system prompt as [key] content. Keys are author-defined (role, intent, tool_usage, …). Values may be inline text, a path string (./prompts/role.md), or {ref: ./path}.
     *
     */
    context?: {
      [k: string]: ContextChunk;
    };
    /**
     * Routing-facing one-liner for delegation tools, AgentCard, and registry discovery. Not injected into the LLM system prompt — use spec.context.* for prompt text. Write from the delegator's perspective.
     *
     */
    description: string;
    /**
     * Preferred model(s) for this agent. Structural intent only — the active flavour selects the actual provider at runtime. Do NOT put api_base or api_key_env here.
     *
     */
    models?: {
      /**
       * Logical model ID within this agent. Use 'main' for the primary model.
       */
      id?: string;
      /**
       * LiteLLM-style model string, e.g. vertex_ai/gemini-3-pro-preview.
       */
      model: string;
      temperature?: number;
      max_tokens?: number;
    }[];
    /**
     * Reasoning strategy. Defaults to react if absent.
     */
    design_pattern?: {
      /**
       * Builtin name shorthand — mutually exclusive with ref. react | cot | cot_native | plan_execute | tree_of_thoughts | accumulator | role aliases. Equivalent to ref: <name> when no scheme prefix.
       *
       */
      type?: string;
      /**
       * Unified plugin locator — mutually exclusive with type. Forms: bare-name, ./local/path, module://pkg.Class, oci://registry/img:tag
       *
       */
      ref?: string;
      /**
       * Plugin-specific design-pattern parameters.
       */
      params?: {
        [k: string]: unknown;
      };
      /**
       * Alias for params (overlay compatibility).
       */
      config?: {
        [k: string]: unknown;
      };
    };
    /**
     * Coordination plugin binding for DelegationContract (how peer delegation executes — transport, limits, parallel policy). The delegation *graph* (which peers) lives on MAS spec.workflow (delegates_to), not here.
     * This release: omit entirely or set type: none. Other type/ref values are rejected at validate/compose. When workflow.type is dynamic, ctl wires the default LlmDelegator at run-mas and exposes delegate_to_<id> tools derived from workflow topology.
     *
     */
    collaboration?: {
      /**
       * Only ``none`` is supported in this release.
       *
       */
      type?: string;
      /**
       * Not supported in this release.
       *
       */
      ref?: string;
      params?: CollaborationParams;
    };
    /**
     * Context window management strategy. Defaults to stack (StackConversation, unbounded history) when absent. Builtin types: stack | sliding-window | summarising | full-history.
     *
     */
    context_manager?: {
      /**
       * Builtin name shorthand — mutually exclusive with ref: stack | sliding-window | summarising | full-history.
       */
      type?: string;
      /**
       * Unified plugin locator — mutually exclusive with type. Same forms as design_pattern.ref.
       */
      ref?: string;
      params?: ContextManagerParams;
      /**
       * Skill names to auto-inject into the system prompt via ContextFacetProvider.  Resolved by the same locator chain as spec.skills (app-local → libraries → packages). This is the context path — complements the tool path (spec.skills → consult_skills tool).
       *
       */
      skills?: string[];
      /**
       * Memory types whose content is auto-injected into the system prompt as context facets.  E.g. [semantic].
       *
       */
      memory?: string[];
    };
    /**
     * Documents to pre-index into the memory backend at startup. Useful for demos and tests that need pre-populated memory without a persistent store.  Each entry is indexed via index_document(source, content, metadata?).
     *
     */
    memory_seed?: MemorySeedEntry[];
    /**
     * Memory configuration for this agent.  Three forms: - String shorthand: "semantic" — resolved to plugin bundle. - Array shorthand: ["semantic", "episodic"] — multiple bundles. - Full object: memory.types, memory.compaction, etc. When absent, the active flavour decides defaults.
     *
     */
    memory?:
      | string
      | string[]
      | {
          /**
           * Master switch.  false = no memory plugins loaded.
           */
          enabled?: boolean;
          /**
           * Ordered list of memory layers to activate.  The runtime instantiates one MemoryProviderPlugin per entry.  When absent, the flavour decides which layers to activate.
           *
           */
          types?: {
            /**
             * Memory layer name: session | episodic | semantic | working | procedural.
             *
             */
            name: string;
            /**
             * Backend implementation: in-memory | file | sqlite-vec | redis | remote_tool.
             *
             */
            backend?: string;
            params?: MemoryBackendParams;
          }[];
          /**
           * Conversation compaction configuration.  Controls how old turns are summarized to stay within the context window.  Maps to the ConversationStrategy used by ContextAssemblerPlugin.
           *
           */
          compaction?: {
            /**
             * Compaction strategy name: keep_recent | summarize | chunked_summarize. chunked_summarize is the OpenClaw-equivalent multi-part strategy.
             *
             */
            strategy?: string;
            /**
             * Minimum tokens reserved for the LLM reply.
             */
            reserve_tokens?: number;
            /**
             * Fraction of recent messages to preserve verbatim (0.0–1.0).
             */
            keep_recent_ratio?: number;
            /**
             * Minimum fraction per compaction chunk.
             */
            min_chunk_ratio?: number;
            /**
             * Buffer multiplier for token estimation error.
             */
            safety_margin?: number;
            /**
             * Preserve opaque identifiers (UUIDs, hashes, URLs, file names) during summarization.  Matches OpenClaw compaction.ts behavior.
             *
             */
            identifier_preservation?: boolean;
            /**
             * Custom instructions prepended to the summarization prompt.
             */
            summarize_instructions?: string;
          };
          /**
           * Session transcript persistence.  Controls where and how conversation history is saved between runs.
           *
           */
          persistence?: {
            /**
             * Persistence backend: none | file | sqlite | redis.
             */
            backend?: string;
            /**
             * Base directory for file-based persistence.  Supports {agent_id} and {session_id} placeholders.  Default when unset: $XDG_DATA_HOME/mas/agents/{agent_id}/sessions/ (see docs/user-config.md).
             *
             */
            path?: string;
            /**
             * Automatically persist after each turn.
             */
            auto_save?: boolean;
            /**
             * Automatically load session on bootstrap.
             */
            auto_load?: boolean;
          };
          /**
           * Semantic memory search configuration.  Controls vector retrieval from the semantic memory layer.
           *
           */
          search?: {
            /**
             * Enable semantic search injection into context.
             */
            enabled?: boolean;
            /**
             * Maximum retrieved chunks per query.
             */
            max_results?: number;
            /**
             * Minimum similarity score threshold.
             */
            min_score?: number;
            chunking?: {
              /**
               * Chunk size in tokens for indexing.
               */
              tokens?: number;
              /**
               * Overlap tokens between chunks.
               */
              overlap?: number;
            };
            /**
             * Hybrid search (vector + full-text) configuration.
             */
            hybrid?: {
              enabled?: boolean;
              vector_weight?: number;
              text_weight?: number;
              /**
               * Max Marginal Relevance re-ranking.
               */
              mmr_enabled?: boolean;
              mmr_lambda?: number;
              temporal_decay_enabled?: boolean;
              temporal_decay_half_life_days?: number;
            };
            cache?: {
              enabled?: boolean;
              max_entries?: number;
            };
          };
          /**
           * Citation formatting for memory search results. Controls whether and how source references are included in search results injected into context.
           *
           */
          citations?: {
            /**
             * Citation mode: auto (include when useful), on (always include), off (strip source info).  Mirrors OpenClaw MemoryCitationsMode.
             *
             */
            mode?: "auto" | "on" | "off";
            /**
             * Maximum characters per search result snippet.
             */
            max_snippet_chars?: number;
          };
          /**
           * File watching and re-indexing synchronization policy. Controls when workspace memory files (MEMORY.md, memory/*.md) are re-indexed into semantic memory.
           *
           */
          sync?: {
            /**
             * Re-index when a session begins.
             */
            on_session_start?: boolean;
            /**
             * Re-index before search (ensures fresh results).
             */
            on_search?: boolean;
            /**
             * Periodic re-index interval in seconds (0 = disabled).
             */
            interval_seconds?: number;
            /**
             * Re-index after this many new messages.
             */
            delta_messages?: number;
            /**
             * Re-index after this many bytes of new content.
             */
            delta_bytes?: number;
            /**
             * Force re-index after compaction.
             */
            post_compaction_force?: boolean;
            /**
             * File change detection settings.
             */
            file_watch?: {
              enabled?: boolean;
              /**
               * Glob patterns to watch for changes.
               */
              patterns?: string[];
              /**
               * Debounce interval for file change detection.
               */
              debounce_ms?: number;
            };
          };
          /**
           * Compaction retry on context overflow.  When an LLM call fails because the context exceeds the window, automatically compact and retry.  Mirrors OpenClaw waitForCompactionRetryWithAggregateTimeout.
           *
           */
          overflow_retry?: {
            /**
             * Enable overflow detection and automatic retry.
             */
            enabled?: boolean;
            /**
             * Maximum compaction+retry attempts.
             */
            max_retries?: number;
            /**
             * Maximum total time for all retries.
             */
            aggregate_timeout_seconds?: number;
            /**
             * Multiply budget by this factor on each retry.
             */
            budget_reduction_factor?: number;
          };
          /**
           * QMD (Qualitative Memory Database) backend configuration. Alternative search via external qmd binary.
           *
           */
          qmd?: {
            /**
             * Enable QMD as a retriever backend.
             */
            enabled?: boolean;
            /**
             * Path to qmd binary (auto-detected if empty).
             */
            binary_path?: string;
            /**
             * Path to QMD index directory.
             */
            index_path?: string;
            /**
             * QMD search mode.
             */
            search_mode?: string;
            max_snippet_chars?: number;
            timeout_seconds?: number;
          };
        };
    /**
     * Skills to activate for this agent.  Each entry is a string with two forms:
     *
     *   # Name only — resolved from the default locator chain:
     *   skills:
     *     - triage-protocol
     *     - memory-protocol
     *
     *   # @library/name — explicit library source:
     *   skills:
     *     - "@sre-skills/triage-protocol"
     *     - "@mas.library.samples/web-search-skill"
     *
     * No file paths, no directory references.  Resolution order: 1. App-local skills/ directory (if present). 2. Libraries declared under 'libraries:' in config.yaml. 3. Installed Python packages.
     *
     */
    skills?: string[];
    /**
     * Logical tool-set name resolved by the infra manifest ToolRegistry. No file paths, no extensions — a simple identifier only. The infra ToolRegistry maps this name to the actual JSON tool-index file path. E.g. sre-tools, backend-tools, verifier-tools.
     *
     */
    tools_ref?: string | null;
    /**
     * Tool declarations for this agent.  Three forms are supported:
     * Form A — ref to a kind: Tool manifest (recommended):
     *   tools:
     *     - ref: ./tools/calculator.tool.yaml
     *     - ref: bundle://sre-tools/check-health   # ToolBundle entry
     *
     * Form B — inline anonymous (backward-compatible):
     *   tools:
     *     - module_path: mas.runtime.tools.calculator_tool
     *       class_name: CalculatorTool
     *
     * Additive with tools_ref — both may be set simultaneously.
     *
     */
    tools?: (
      | string
      | {
          /**
           * Path to a kind: Tool manifest (./tools/calculator.tool.yaml) or a ToolBundle entry reference (bundle://sre-tools/check-health).
           *
           */
          ref: string;
          /**
           * Registration priority (higher = loaded first).
           */
          priority?: number;
        }
      | {
          /**
           * Implementation kind — defaults to python. python  — ToolContract subclass loaded via module_path. remote_tool — remote tool-server tool; module_path points to ToolServerClient adapter. openapi — OpenAPI endpoint; module_path points to OpenAPITool adapter.
           *
           */
          kind?: "python" | "remote_tool" | "openapi";
          /**
           * Dotted Python module path, e.g. mas.runtime.tools.calculator_tool. May also be a relative filesystem path (./tools/my_tool.py).
           *
           */
          module_path: string;
          /**
           * Class name in the module. Auto-discovered when omitted.
           */
          class_name?: string;
          /**
           * Registration priority (higher = loaded first).
           */
          priority?: number;
          /**
           * Optional tool-specific init params.
           */
          params?: {
            [k: string]: unknown;
          };
        }
    )[];
    /**
     * Plugin instances to load into this agent's registry. Processed in order — use priority to control execution ordering within hook chains. Overlay-compatible: an overlay may append entries to this list or override a named entry (matched by the name field).
     *
     */
    plugins?: {
      /**
       * Logical name for this plugin instance. Used as a stable key for overlay merge and registry lookup. Defaults to class_name when omitted.
       *
       */
      name?: string;
      /**
       * Dotted Python module path, e.g. mas.runtime.plugins.guardrails_plugin.
       */
      module_path: string;
      /**
       * Plugin class name to instantiate.
       */
      class_name: string;
      /**
       * Plugin-specific init kwargs passed as plugin_cls(**config).
       */
      config?: {
        [k: string]: unknown;
      };
      /**
       * Alias for config (backward compatibility).
       */
      params?: {
        [k: string]: unknown;
      };
      /**
       * Execution order within a hook chain. Lower = earlier.
       */
      priority?: number;
      /**
       * Set to false to disable this plugin without removing it.
       */
      enabled?: boolean;
    }[];
    /**
     * Per-agent runtime behavior configuration. These settings are structural/semantic — they affect what system tools and capabilities are exposed to this agent's LLM at runtime. Do NOT put secrets, API keys, or deployment config here (use flavour.yaml).
     *
     */
    behavior?: {
      /**
       * When true, the send_to_caller tool exposes an optional reasoning_context parameter.  The sub-agent can (but is not required to) provide a concise summary of HOW it reached its answer — not its message history, but key evidence, decision points, and confidence signals. Forwarded to the orchestrator as result["reasoning"] so it can bridge the reasoning-context gap between delegation and synthesis. Privacy-by-default: false.  Enable only for trusted internal agents where context leakage is acceptable.
       *
       */
      share_reasoning?: boolean;
      /**
       * Controls which delegation tools are registered for this agent.
       * typed (only value in this release): delegate_to_<id> tools derived from MAS workflow.delegates_to when workflow.type is dynamic. Peer IDs are fixed at compose time — the LLM cannot call agents outside the topology.
       * generic (delegate_task with free-form agent_id) is a design target — not implemented in OSS; see ROADMAP.
       *
       */
      delegation_style?: "typed";
    };
    governance?: GovernanceBinding;
    llm?: LlmBinding;
    execution?: ExecutionBinding;
    control?: ControlBinding;
    observability?: ObservabilityBinding;
    /**
     * Infra manifest references (LLM proxy, tool registry). Merged additively from overlays.
     *
     */
    infra_refs?: string[];
    /**
     * Cross-cutting infra middleware (cache, chaos, …) outer-first in front of merged infra_refs providers.
     *
     */
    infra_interceptors?: string[];
  };
}
/**
 * CollaborationPlugin constructor kwargs (design). Not used when spec.collaboration is omitted or type is none in this release.
 *
 */
export interface CollaborationParams {
  max_delegations?: number;
  allow_parallel?: boolean;
}
/**
 * ContextManagerPlugin constructor kwargs.
 */
export interface ContextManagerParams {
  /**
   * Sliding-window / summarising — max prior exchange pairs.
   */
  max_turns?: number;
  /**
   * Alias for max_turns (sliding-window).
   */
  window_size?: number;
  /**
   * Stack CM — cap total past messages.
   */
  max_messages?: number;
  /**
   * Slice size for working_memory context source (default 20).
   */
  working_memory_messages?: number;
  /**
   * Max estimated input tokens after assembly.
   */
  token_budget?: number;
  /**
   * Alias for token_budget.
   */
  max_tokens?: number;
  /**
   * Tokens reserved for model completion (default 512).
   */
  reserve_tokens?: number;
  /**
   * Summarising CM — token threshold before compression.
   */
  summary_threshold?: number;
  /**
   * Summarising CM — recent pairs kept verbatim.
   */
  keep_turns?: number;
  /**
   * Registry ref for working_memory context source plugin.
   */
  working_memory_ref?: string;
  /**
   * Registry ref for token-budget trimmer plugin.
   */
  trimmer_ref?: string;
  /**
   * Alias for trimmer_ref.
   */
  token_budget_ref?: string;
}
/**
 * Inline memory seed — maps to MemorySeedLoader (key/source + content).
 */
export interface MemorySeedEntry {
  key?: string;
  source?: string;
  id?: string;
  content: string;
  text?: string;
}
/**
 * MemoryProvider backend constructor kwargs.
 */
export interface MemoryBackendParams {
  path?: string;
  url?: string;
  collection?: string;
  host?: string;
  port?: number;
  database?: string;
}
/**
 * GovernancePlugin declarative policy — maps to PolicyDefinition.
 */
export interface PolicyRule {
  name: string;
  enabled?: boolean;
  action: "hitl" | "block" | "terminate" | "log" | "modify" | "skip" | "retry" | "blacklist";
  trigger: {
    true?:
      | "tool_input"
      | "tool_output"
      | "llm_output"
      | "delegation_output"
      | "budget_threshold"
      | "event"
      | "tool_failure_streak";
    tool?: string;
    condition?: string;
    evaluation?: string;
    threshold?: number;
    reset_on?: string;
  };
  params?: {};
  recovery?: {};
}
/**
 * GovernancePlugin declarative policy — maps to PolicyDefinition.
 */
export interface PolicyRule1 {
  name: string;
  enabled?: boolean;
  action: "hitl" | "block" | "terminate" | "log" | "modify" | "skip" | "retry" | "blacklist";
  trigger: {
    true?:
      | "tool_input"
      | "tool_output"
      | "llm_output"
      | "delegation_output"
      | "budget_threshold"
      | "event"
      | "tool_failure_streak";
    tool?: string;
    condition?: string;
    evaluation?: string;
    threshold?: number;
    reset_on?: string;
  };
  params?: {};
  recovery?: {};
}
/**
 * EngineContract / LiveLlmEngine parameters — not free-form config.
 */
export interface LlmBinding {
  model?: string;
  /**
   * Engine provider hint (mock, openai, azure, …).
   */
  provider?: string;
  temperature?: number;
  max_tokens?: number;
}
/**
 * EngineContract execution mode — mock/live/cache/parallel only.
 */
export interface ExecutionBinding {
  mocking?: {
    enabled?: boolean;
  };
  cache?: {
    enabled?: boolean;
  };
  parallel?: boolean;
  live?: boolean;
  timeout?: number;
}
/**
 * Control-plane plugin configs keyed by plugin id. Set a key to null to disable. Each value is passed to the registered control plugin only.
 *
 */
export interface ControlBinding {
  budget?: null | {
    max_tokens?: number;
    max_cost_usd?: number;
  };
  circuit_breaker?: null | {
    failure_threshold?: number;
    reset_timeout_s?: number;
  };
  rate_limiter?: null | {
    requests_per_minute?: number;
  };
}
