//  Copyright (c) 2026 Cisco Systems, Inc. and its affiliates
//  SPDX-License-Identifier: Apache-2.0
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for kind: MAS manifests (apiVersion: mas/v1). Authoritative field list is derived from MASSpec in mas.py. Validate with: python -m jsonschema --instance mas.yaml mas.schema.yaml
 *
 */
export interface MASManifest {
  apiVersion: "mas/v1";
  kind: "MAS";
  /**
   * Optional: what this system knows and can do. Consumed by user emulation agents (mas-lab) and agent card queries.
   */
  intent?: {
    summary?: string;
  };
  /**
   * Alias for intent (backward compatibility). Prefer 'intent'.
   */
  mas_intent?: {
    summary?: string;
  };
  metadata: {
    /**
     * Unique MAS identifier. Used in run output paths and agent URNs.
     */
    name: string;
    version?: string;
    description?: string;
    tags?: string[];
    /**
     * Name of the flavour to use when none is specified on the CLI.
     */
    default_flavour?: string;
  };
  spec: {
    /**
     * Short form: flat list of agent refs (equivalent to agency.agents). Accepted alongside or instead of agency.agents for convenience.
     *
     */
    agents?: {
      id?: string;
      ref: string;
    }[];
    /**
     * Transport / communication protocol config.
     */
    transport?: {
      type?: "agent-local" | "agent-remote";
      mode?: "local" | "remote";
      /**
       * When true, delegation uses in-process function calls (no HTTP).
       */
      emulation?: boolean;
    };
    /**
     * The agents and their topology.
     */
    agency?: {
      /**
       * Ordered list of agent participants with their structural role and delegation targets.
       */
      agents?: {
        /**
         * Logical identifier used in workflow edges and delegation lists.
         */
        id?: string;
        /**
         * Path to the agent manifest, relative to the MAS manifest directory.
         */
        ref: string;
      }[];
    };
    /**
     * Workflow topology — entry point and delegation graph.
     */
    workflow?: {
      /**
       * Workflow strategy: - dynamic: broker agent decides delegation order dynamically (default) - sequential: automaton walks edges in declared order, accumulating context
       *
       */
      type?: "dynamic" | "sequential" | "async_dynamic" | "graph" | "supervised";
      /**
       * ID of the entry-point agent (first to receive the user request).
       */
      entry?: string;
      /**
       * Agent nodes in the workflow graph.
       */
      nodes?: {
        id?: string;
        role?: string;
        delegates_to?: string[];
        [k: string]: unknown;
      }[];
      /**
       * Legacy: directed communication edges between agents.
       */
      edges?: {
        from: string;
        to: string[];
      }[];
    };
    /**
     * MAS-level logical tool-set name resolved by the infra ToolRegistry. Provides a default tool set for agents that do not declare their own spec.tools_ref. No file paths or extensions. E.g. sre-tools, shared-tools.
     *
     */
    tools_ref?: string | null;
    /**
     * List of infra manifest paths (relative to the MAS manifest directory). Equivalent to infra_refs in a flavour; allows projects to register a ToolRegistry directly in mas.yaml without a per-project flavours/local.yaml. E.g. [tool-registry.yaml]
     *
     */
    infra_refs?: string[];
    /**
     * Middleware config (reserved for future use).
     */
    middleware?: {
      [k: string]: unknown;
    };
    /**
     * Named memory store artifact paths.
     */
    memory_stores?: {
      episodic_ref?: string;
      semantic_ref?: string;
      procedural_ref?: string;
    };
    /**
     * Telemetry output config.
     */
    telemetry?: {
      /**
       * Path to the event log file (JSONL), relative to mas.yaml.
       */
      path?: string;
    };
  };
}
