/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for kind: MAS manifests (apiVersion: mas/v1). Authoritative field list is derived from MASSpec in mas.py. Validate with: python -m jsonschema --instance mas.yaml mas.schema.yaml
 *
 */
export interface MASManifest {
  apiVersion: "mas/v1";
  kind: "MAS";
  /**
   * Optional: what this system knows and can do.
   */
  intent?: {
    summary?: string;
  };
  /**
   * UI-only: React Flow node positions (not consumed by runtime).
   */
  "x-canvas-positions"?: {
    [k: string]: {
      x: number;
      y: number;
    };
  };
  metadata: {
    /**
     * Unique MAS identifier. Used in run output paths and agent URNs.
     */
    name: string;
    version?: string;
    description?: string;
    tags?: string[];
    /**
     * Name of the flavour to use when none is specified on the CLI.
     */
    default_flavour?: string;
  };
  spec: {
    /**
     * Short form: flat list of agent refs (equivalent to agency.agents).
     *
     */
    agents?: (
      | {
          id?: string;
          ref: string;
        }
      | {
          apiVersion?: "mas/v1";
          kind: "Agent";
          metadata: {
            [k: string]: unknown;
          };
          spec: {
            [k: string]: unknown;
          };
        }
    )[];
    /**
     * Transport / communication protocol config.
     */
    transport?: {
      type?: "local" | "agent-remote" | "agent-local";
      mode?: "local" | "remote";
      /**
       * When true, delegation uses in-process function calls (no HTTP).
       */
      emulation?: boolean;
    };
    /**
     * Framework surface adapter for this MAS use-case. Selects which ctl/lab wrapper mounts around the native machinery skeleton (not an alternate kernel). Lab infers the runner from default_adapter unless execution.runner overrides.
     *
     */
    framework?: {
      /**
       * Framework adapter id. native = direct default OSS kernel; others delegate to registered ctl framework wrappers (future release).
       *
       */
      default_adapter?: "native" | "langgraph" | "autogen" | "crewai";
    };
    /**
     * The agents and their topology.
     */
    agency?: {
      /**
       * Ordered list of agent participants and delegation targets.
       */
      agents?: (
        | {
            /**
             * Logical identifier used in workflow edges and delegation lists.
             */
            id?: string;
            /**
             * Path to the agent manifest, relative to the MAS manifest directory.
             */
            ref: string;
          }
        | {
            apiVersion?: "mas/v1";
            kind: "Agent";
            metadata: {
              [k: string]: unknown;
            };
            spec: {
              [k: string]: unknown;
            };
          }
      )[];
    };
    /**
     * Workflow topology — entry point and delegation graph.
     */
    workflow?: {
      /**
       * Workflow strategy: dynamic, sequential, hybrid, or single.
       *
       */
      type?: "dynamic" | "sequential" | "hybrid" | "single";
      /**
       * Filesystem path to a Python module registering the workflow via WorkflowContract.register_impl().
       *
       */
      plugin?: string;
      /**
       * ID of the entry-point agent (first to receive the user request).
       */
      entry?: string;
      /**
       * Supervised / verifier workflow round cap.
       */
      max_rounds?: number;
      /**
       * Agent nodes in the workflow graph.
       */
      nodes?: WorkflowNode[];
    };
    /**
     * MAS-level logical tool-set name resolved by the infra ToolRegistry.
     */
    tools_ref?: string | null;
    /**
     * Infra manifest paths relative to the MAS manifest directory.
     */
    infra_refs?: string[];
    /**
     * Middleware config (reserved for future use).
     */
    middleware?: {
      [k: string]: unknown;
    };
    /**
     * Named memory store artifact paths.
     */
    memory_stores?: {
      episodic_ref?: string;
      semantic_ref?: string;
      procedural_ref?: string;
    };
    /**
     * Telemetry output config.
     */
    telemetry?: {
      /**
       * Path to the event log file (JSONL), relative to mas.yaml.
       */
      path?: string;
    };
  };
}
/**
 * MAS workflow graph node — id, delegation targets, optional role/config.
 */
export interface WorkflowNode {
  id: string;
  role?: string;
  agent?: string;
  delegates_to?: string[];
  /**
   * Parallel topology dispatch mode (e.g. all).
   */
  dispatch?: string;
  /**
   * Plugin-specific parameters (pattern-dependent keys allowed).
   */
  config?: {
    [k: string]: unknown;
  };
  description?: string;
}
