#!/usr/bin/env python3
#  Copyright (c) 2026 Cisco Systems, Inc. and its affiliates
#  SPDX-License-Identifier: Apache-2.0
"""Generate docs/includes/mas-paths.md from mas.runtime constants.

MkDocs (pymdownx.snippets) include example::

    --8<-- "docs/includes/mas-paths.md:xdg-user-config"

Run via ``task docs-gen`` or ``python3 scripts/gen_doc_paths.py``.
"""
from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
RUNTIME_SRC = REPO_ROOT / "runtime" / "src"
OUTPUT = REPO_ROOT / "docs" / "includes" / "mas-paths.md"


def _imports():
    if str(RUNTIME_SRC) not in sys.path:
        sys.path.insert(0, str(RUNTIME_SRC))
    from mas.runtime.constants import WORKSPACE_CONFIG_FILENAME
    from mas.runtime.xdg import (
        AGENT_MEMORY_SOURCE,
        AGENT_SESSIONS_SOURCE,
        ARTIFACTS_CACHE_SOURCE,
        CONTROLLER_SOCKET_SOURCE,
        LABS_DIR_SOURCE,
        LAST_RUN_SOURCE,
        MAS_HOME_SOURCE,
        RUNS_DIR_SOURCE,
        TRACE_CACHE_SOURCE,
        USER_CONFIG_SOURCE,
    )

    return {
        "workspace-config-filename": WORKSPACE_CONFIG_FILENAME,
        "xdg-user-config": USER_CONFIG_SOURCE,
        "xdg-labs-dir": LABS_DIR_SOURCE,
        "xdg-runs-dir": RUNS_DIR_SOURCE,
        "xdg-trace-cache": TRACE_CACHE_SOURCE,
        "xdg-artifacts-cache": ARTIFACTS_CACHE_SOURCE,
        "xdg-last-run": LAST_RUN_SOURCE,
        "xdg-agent-sessions": AGENT_SESSIONS_SOURCE,
        "xdg-agent-memory": AGENT_MEMORY_SOURCE,
        "mas-home": MAS_HOME_SOURCE,
        "controller-socket": CONTROLLER_SOCKET_SOURCE,
    }


def generate_mas_paths_snippet() -> str:
    sections = _imports()
    lines = [
        "<!--",
        "  Copyright (c) 2026 Cisco Systems, Inc. and its affiliates",
        "  SPDX-License-Identifier: Apache-2.0",
        "-->",
        "<!-- Auto-generated by scripts/gen_doc_paths.py — do not edit; run task docs-gen -->",
        "",
    ]
    for name, value in sections.items():
        lines.extend(
            [
                f"--8<-- [start:{name}]",
                value,
                f"--8<-- [end:{name}]",
                "",
            ]
        )
    return "\n".join(lines)


def main() -> int:
    content = generate_mas_paths_snippet()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"  → wrote {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
