apiVersion: mas/v1
kind: Overlay
metadata:
  name: react-moderator
spec:
  target:
    kind: MAS
  patch:
    agents:
      moderator:
        design_pattern:
          type: react
          config:
            max_steps: 10
x-namespace: global
x-canvas-positions:
  node_0ae0343f:
    x: 912
    y: 96
  node_3eedcf04:
    x: 496
    y: 96
x-canvas-node-ids:
  moderator:
    agent: node_0ae0343f
    designPattern: node_3eedcf04
