apiVersion: mas/v1
kind: Overlay
metadata:
  name: reflection-moderator
spec:
  target:
    kind: MAS
  patch:
    agents:
      moderator:
        design_pattern:
          type: react
          config:
            max_steps: 10
x-namespace: global
x-canvas-positions:
  node_3ef1a08a:
    x: 704
    y: 128
  node_55808455:
    x: 208
    y: 128
x-canvas-node-ids:
  moderator:
    agent: node_3ef1a08a
    designPattern: node_55808455
