#  Copyright (c) 2026 Cisco Systems, Inc. and its affiliates
#  SPDX-License-Identifier: Apache-2.0
apiVersion: mas/v1
kind: Overlay
metadata:
  name: reflection
spec:
  target:
    kind: MAS
  patch:
    agents:
      moderator:
        design_pattern:
          type: reflection
          config:
            max_steps: 10
x-canvas-positions:
  node_75bc8a11:
    x: 752
    y: 160
  node_c6f30471:
    x: 384
    y: 96
x-canvas-node-ids:
  moderator:
    agent: node_75bc8a11
    designPattern: node_c6f30471
